### ISSUE TITLE
Fail to verify certificate

### ISSUE THREAD

**Issue by danielterwiel** [MioQuispe/ic-starter-templates#1]
I followed the instructions in the README.md, I can launch the boilerplate project, but whenever I hit the counter button something seems wrong regarding certification. My guess would be that something is not in order with [certification](https://sdk.dfinity.org/docs/interface-spec/index.html#certification) but I wonder how to approach this.

Specs

```
dfx 0.7.0-beta.8
Ubuntu 20.04.2 LTS
Node v16.1.0
npm 7.13.0
```

Vite config:
* React 
* No TypeScript

![image](https://user-images.githubusercontent.com/25886902/118363599-7275a800-b595-11eb-9d35-e7cbf7f4a94b.png)

P.S. thanks for this project 🙏

**Comment by dostro** [comment]
+1 for this issue

**Comment by MioQuispe** [comment]
> I followed the instructions in the README.md, I can launch the boilerplate project, but whenever I hit the counter button something seems wrong regarding certification. My guess would be that something is not in order with [certification](https://sdk.dfinity.org/docs/interface-spec/index.html#certification) but I wonder how to approach this.
> 
> Specs
> 
> ```
> dfx 0.7.0-beta.8
> Ubuntu 20.04.2 LTS
> Node v16.1.0
> npm 7.13.0
> ```
> 
> Vite config:
> 
> * React
> * No TypeScript
> 
> ![image](https://user-images.githubusercontent.com/25886902/118363599-7275a800-b595-11eb-9d35-e7cbf7f4a94b.png)
> 
> P.S. thanks for this project

Thanks for reporting it! I'm getting the same issue, sorry about that. Will fix it asap.

**Comment by MioQuispe** [comment]
@dostro @danielterwiel I found the issue. The latest @dfinity/agent is broken it seems. Fix the version in package.json:
```
"@dfinity/agent": "0.8.6",
```
See I removed the ^ in front. It was installing 0.8.9 otherwise, which seems to be broken. I will add do that for the templates as well.

**Comment by dostro** [comment]
@MioQuispe thank you 🙏
