### ISSUE TITLE
Can't find variable require after deploying canisters

### ISSUE THREAD

**Issue by dostro** [MioQuispe/ic-starter-templates#2]
Following readme and can run `npm run dev`, but won't run from deployed canisters

dfx 0.7.0-beta.8
node v14.15.4
npm 6.14.10
MacOS 11.3.1

Vite config with React and JS

<img width="1467" alt="Screen Shot 2021-05-16 at 11 59 55 AM" src="https://user-images.githubusercontent.com/2414917/118403956-e4ee9280-b63e-11eb-8269-075cacae931c.png">

**Comment by MioQuispe** [comment]
> Following readme and can run `npm run dev`, but won't run from deployed canisters
> 
> dfx 0.7.0-beta.8
> node v14.15.4
> npm 6.14.10
> MacOS 11.3.1
> 
> Vite config with React and JS
> 
> <img alt="Screen Shot 2021-05-16 at 11 59 55 AM" width="1467" src="https://user-images.githubusercontent.com/2414917/118403956-e4ee9280-b63e-11eb-8269-075cacae931c.png">

:sob: investigating

**Comment by MioQuispe** [comment]
> Following readme and can run `npm run dev`, but won't run from deployed canisters
> 
> dfx 0.7.0-beta.8
> node v14.15.4
> npm 6.14.10
> MacOS 11.3.1
> 
> Vite config with React and JS
> 
> <img alt="Screen Shot 2021-05-16 at 11 59 55 AM" width="1467" src="https://user-images.githubusercontent.com/2414917/118403956-e4ee9280-b63e-11eb-8269-075cacae931c.png">

change to 0.8.7 Lol
I forgot 0.8.6 still had this problem. Sorry about the inconvenience.

**Comment by MioQuispe** [comment]
Pushed fix.

**Comment by dostro** [comment]
All good, thank you (again) 

:)
